spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qq331173500
    url: jdbc:mysql://127.0.0.1:3305/security_demo

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl